version: 0.2
phases:
  pre_bild:
    commands:
      - echo Restore started on `date`
      - dotnet restore api-code-deploy.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output api-code-deploy.csproj
artifacts:
  files:
     - build_output/**/*
     - deploy-scripts/**/*
     - appspec.yml